### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by flahol**

### CODE REVIEW

**Comment by kurisuD** [comment]
too many sudo in the instructions?

**Comment by drdaeman** [comment]
Just a suggestion - if readme mentions `apt-get` how about mentioning a proper way to set up things by building a package and installing it?

Something like `git-buildpackage --git-upstream-tree=master` then `sudo dpkg -i ../hubicfuse*.deb`, while not perfect, is much cleanlier than any `sudo make install`, as the files would be properly managed. (Although `debian/` is currently from cloudfuse and has a wrong package name - I suppose this is an independent issue worth fixing.)

Obviously, that applies only to Debian and derivatives.

**Comment by TurboGit** [comment]
Sounds good. Can you provide a patch for this?

**Comment by drdaeman** [comment]
Sure. Will do, but more likely not today but tomorrow or the day after tomorrow - I have to find some spare time and freshen my memory on Debian packaging guidelines in hope to do not just a packaging, but policy-compliant one that would be hopefully suitable for inclusion in distros if someone would dare to become a maintainer.

**Comment by TurboGit** [comment]
Thanks, there certainly ain't any urgency!

**Comment by TurboGit** [comment]
Ping?

Should I just close this MR?

**Comment by flahol** [comment]
ok for me
    
    Le 10/11/2015 22:26, Pascal Obry a
      écrit :
    
    
      Ping?
      Should I just close this MR?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
Patrice Flahault

**Comment by TurboGit** [comment]
Closed then!

**Pull request closed without merging**
