### PR TITLE
Utimens support, several fixes and speed improvements

### PR DESCRIPTION
**Pull request by dan-cristian**
First release attempt. I run several tests and seems stable. Has plenty debugging code in it, might be worth trying a merge on a different branch?

Recent additions/fixes (from https://github.com/dan-cristian):
	* Support for atime, mtime, chmod, chown.
	* Large files (segmented) have correct size listed (was 0 before).
	* Multiple speed improvements, minimised the number of HTTP calls and added more caching features.
	* Fixed many segmentation faults.
	* Cached files are deleted on cache expiration when using a custom temp folder.
	* Files copied have attributes preserved.
	* Working well with rsync due to mtime support and proper copy operations.
	* Support for http progress (track upload / download speed etc.)
	* Major code refactoring, code documentation, extensive debugging, additional config options

### CODE REVIEW

**Comment by TurboGit** [comment]
Ok you've made a tremendous amount of valuable work but it is almost impossible to review as-is. Others have already said that it is working fine. But next step is to present the change-set in a step by step commits easy to review.

What can I do to help here?

Do you know how to merge multiple commit or reorder them? Do you know how to delete unneeded commits?

Let me know how, I'd like all this to be integrated as soon as possible. Thanks.

**Comment by TurboGit** [comment]
Maybe the best solution is to merge all commits into a single commit and then from there get all modifications and using (git gui) commit bit & pieces (possible even for a single line) for each new feature and bug fix. The goal being having a separate commit for each new feature or bug fix if possible. Again if you need help with some Git incantation, tell us!

**Comment by dan-cristian** [comment]
I merged all commits with git reset --soft HEAD~x and forced a push, other methods seems very time consuming given the large amount of changes. I think I cannot really separate the commits by features due to significant code refactoring. This merge request should be closed and will open a new one.

**Comment by dan-cristian** [comment]
new pull request created, closing this one

**Pull request closed without merging**
