### PR TITLE
possibility to mount multiple accounts

### PR DESCRIPTION
**Pull request by nikokio**
A small change in order to be able to mount multiple accounts by passing, optionally, the settings filename as a "-o" argument (see README file)

Please be kind in your comments as I'm very new to github and didn't write a single line of C for years !

Thanks

### CODE REVIEW

**Comment by jpierre03** [comment]
@TurboGit do you have an idea on this PR ?

**Comment by TurboGit** [comment]
Sorry it felt through the cracks :( Seems interesting, I'll try to have a look this week.

**Comment by TurboGit** [comment]
BTW, have you tested it? Is it working for you?

**Comment by nikokio** [comment]
Hello,

Not sure who you ask the question to. I do use it since the day I pushed it, so for 7 month now, on 3 always-on servers.

Thanks

**Comment by TurboGit** [comment]
Thanks!

**Pull request merged**
